moneycontrol_mid_cap = [
    "https://www.moneycontrol.com/mutual-funds/nav/hsbc-mid-cap-fund-direct-plan/MCC275#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/invesco-india-midcap-fund-direct-plan/MLI556#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/edelweiss-mid-cap-fund-direct-plan/MJP117#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/icici-prudential-midcap-fund-direct-plan/MPI1150#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/whiteoak-capital-mid-cap-fund-direct-plan-/MWC007#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/iti-mid-cap-fund-direct-plan/MIT055#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/helios-mid-cap-fund-direct-plan-growth/MHMA019#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/mahindra-manulife-mid-cap-fund-direct-plan-growth/MMH037#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/jm-midcap-fund-direct/MJM484#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/mirae-asset-midcap-fund-direct-plan/MMA173#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/bnp-paribas-mid-cap-fund-direct-plan/MAB726#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/bandhan-midcap-fund-direct-plan-growth/MAG2158#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/union-midcap-fund-direct-plan/MUK152#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/aditya-birla-sun-life-midcap-fund-direct-plan/MBS829#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/hdfc-mid-cap-opportunities-fund-direct-plan/MHD1161#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/sbi-midcap-fund-direct-plan/MSB505#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/lic-mf-mid-cap-fund-direct-plan-growth/MIB230#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/nippon-india-growth-fund-direct-plan/MRC919#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/sundaram-mid-cap-fund-direct-plan/MSN568#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/tata-mid-cap-growth-fund-direct-plan/MTA776#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/axis-mid-cap-fund-direct-plan/MAA194#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/kotak-midcap-fund-direct-plan/MKM528#holdings",
    "https://www.moneycontrol.com/mutual-funds/nav/canara-robeco-mid-cap-fund-direct-plan/MCA338#holdings",

]